# autogradepro-frontend/docker-compose.yml
#version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autogradepro-frontend
    networks:
      - app_network
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  app_network:
    external: true
    name: autogradepro_network
